import aQute.bnd.gradle.BundleTaskConvention

import com.liferay.gradle.util.FileUtil
import com.liferay.gradle.util.copy.StripPathSegmentsAction

configurations {
	dummy
}

task buildSystemPackagesExtraManifest(type: Jar)
task copySystemPackagesExtraManifest(type: Copy)

File systemPackagesExtraBndFile = file("system.packages.extra.bnd")
File systemPackagesExtraManifestFile = file("system.packages.extra.mf")

buildSystemPackagesExtraManifest {
	convention.plugins.bundle = new BundleTaskConvention(it)
	bndfile = systemPackagesExtraBndFile
	configuration = configurations.dummy
	dependsOn copyLibs
	destinationDir = new File(temporaryDir, "bundle")

    doLast {
        buildBundle()
		copy {
			eachFile new StripPathSegmentsAction(1)
			from zipTree(archivePath)
			include "META-INF/MANIFEST.MF"
			into systemPackagesExtraManifestFile.parentFile

			rename {
				systemPackagesExtraManifestFile.name
			}
		}
    }

	from sourceSets.main.output
}

copySystemPackagesExtraManifest {
	if (!FileUtil.isUpToDate(project, systemPackagesExtraBndFile, systemPackagesExtraManifestFile)) {
		dependsOn buildSystemPackagesExtraManifest
	}

	from systemPackagesExtraManifestFile
	into "tmp/META-INF"

	rename {
		"MANIFEST.MF"
	}
}

dependencies {
	compile group: "com.liferay.portal", name: "portal-impl", version: liferay.portalVersion
	compile group: "com.liferay.portal", name: "portal-service", version: liferay.portalVersion
	compile group: "javax.servlet", name: "javax.servlet-api", version: "3.0.1"
	compile group: "javax.xml.ws", name: "jaxws-api", version: "2.2.11"
	compile group: "org.springframework", name: "spring-beans", version: "3.2.10.RELEASE"
	compile group: "org.springframework", name: "spring-context", version: "3.2.10.RELEASE"
	compile project(":core:jaxws-osgi-bridge")
	compile project(":core:osgi-service-tracker-map")
	compile project(":core:registry-impl")
}

deploy {
	from("lib") {
		include "com.liferay.osgi.servicetrackermap.jar"
		include "org.eclipse.osgi.jar"
		include "registry-impl.jar"
	}
}

jar {
	dependsOn copySystemPackagesExtraManifest
}

liferay {
	deployDir = file("${liferayHome}/osgi/core")
}