apiVersion: apps/v1
kind: Deployment
metadata:
  name: customrestservice
  labels:
    app: customrestservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customrestservice
  template:
    metadata:
      labels:
        app: customrestservice
    spec:
      containers:
      - name: customrestservice
        image: customrestservice
        imagePullPolicy: Never
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        - containerPort: 8000
        env:
          - name: AMADEUS_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: amadeus-credentials-configmap
                key: AMADEUS_CLIENT_ID
          - name: AMADEUS_CLIENT_SECRET
            valueFrom:
              configMapKeyRef:
                name: amadeus-credentials-configmap
                key: AMADEUS_CLIENT_SECRET
        volumeMounts:
        - mountPath: /etc/liferay/lxc/dxp-metadata
          name: lxc-dxp-metadata
          readOnly: true
        - mountPath: /etc/liferay/lxc/ext-init-metadata
          name: lxc-ext-init-metadata
          readOnly: true
      volumes:
        - name: lxc-dxp-metadata
          configMap:
            name: lxc-dxp-metadata
        - name: lxc-ext-init-metadata
          configMap:
            name: customrestservice-lxc-ext-init-metadata
