apiVersion: apps/v1
kind: Deployment
metadata:
  name: designpackfire
  labels:
    app: designpackfire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: designpackfire
  template:
    metadata:
      labels:
        app: designpackfire
    spec:
      containers:
      - name: designpackfire
        image: designpackfire
        imagePullPolicy: Never
        resources:
          limits:
            memory: "50Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/liferay/lxc/dxp-metadata
          name: lxc-dxp-metadata
          readOnly: true
        - mountPath: /etc/liferay/lxc/ext-init-metadata
          name: lxc-ext-init-metadata
          readOnly: true
      volumes:
        - name: lxc-dxp-metadata
          configMap:
            name: lxc-dxp-metadata
        - name: lxc-ext-init-metadata
          configMap:
            name: designpackfire-lxc-ext-init-metadata
            optional: true
