@startuml Discover Static LXC Extension
!include common.wsd
title Discover Static LXC Extension
actor developer
participant lcp
participant api
box "Kubernetes cluster"
    participant "k8s-api" as k8s
    participant dxp
    participant extension
end box

dxp -> k8s : watch for\next-configmaps
developer -> lcp : deploy\nextension
lcp -> api : upload\nextension
api -> api : parse\nextension\nLCP.json &\nconfigurations
par this happens in parallel
api -> k8s : create\nextension\ndeployment
k8s -> extension : create\nextension\npods
activate extension
else
api -> k8s : create\next-configmap
k8s -> dxp : announce\next-configmap
dxp -> dxp : creates OSGi\nconfiguration
end

@enduml