@startuml Discover LXC Extension having OAuth2 Profile
!include common.wsd
title Discover LXC Extension having OAuth2 Profile
actor developer
participant lcp
participant api
participant extension
participant k8s
participant dxp

dxp -> k8s : watch for\next-configmaps
developer -> lcp : deploy\nextension
lcp -> api : upload\nextension
api -> api : parse\nextension\nLCP.json &\nconfigurations
api -> k8s : create\nextension\ndeployment\ndependent on\ndxp-configmap
k8s -> extension : create\nextension\npods\ndependent on\ndxp-configmap
api -> k8s : create\next-configmap
k8s -> dxp : announce\next-configmap
dxp -> k8s : create\ndxp-configmap
k8s -> extension : announce\ndxp-configmap

@enduml