apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  labels:
    app: cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cronjob
            image: cronjob
            resources:
              limits:
                memory: "100Mi"
                cpu: "10m"
            volumeMounts:
            - mountPath: /etc/liferay/lxc/dxp-metadata
              name: lxc-dxp-metadata
              readOnly: true
            - mountPath: /etc/liferay/lxc/ext-init-metadata
              name: lxc-ext-init-metadata
              readOnly: true
          volumes:
            - name: lxc-dxp-metadata
              configMap:
                name: lxc-dxp-metadata
            - name: lxc-ext-init-metadata
              configMap:
                name: cronjob-lxc-ext-init-metadata
