apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  labels:
    app: cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cronjob
            image: cronjob
            resources:
              limits:
                memory: "100Mi"
                cpu: "10m"
            env:
              - name: LIFERAY_OAUTH2_HEADLESS_SERVER_CLIENT_ID
                valueFrom:
                  configMapKeyRef:
                    key: liferay_oauth2_headless_server_client_id
                    name: cronjob.extension.liferay.com
              - name: LIFERAY_OAUTH2_HEADLESS_SERVER_CLIENT_SECRET
                valueFrom:
                  configMapKeyRef:
                    key: liferay_oauth2_headless_server_client_secret
                    name: cronjob.extension.liferay.com
              - name: LIFERAY_OAUTH2_AUTHORIZATION_URI
                valueFrom:
                  configMapKeyRef:
                    key: liferay_oauth2_authorization_uri
                    name: cronjob.extension.liferay.com
              - name: LIFERAY_OAUTH2_INTROSPECTION_URI
                valueFrom:
                  configMapKeyRef:
                    key: liferay_oauth2_introspection_uri
                    name: cronjob.extension.liferay.com
              - name: LIFERAY_OAUTH2_REDIRECT_URIS
                valueFrom:
                  configMapKeyRef:
                    key: liferay_oauth2_redirect_uris
                    name: cronjob.extension.liferay.com
              - name: LIFERAY_OAUTH2_TOKEN_URI
                valueFrom:
                  configMapKeyRef:
                    key: liferay_oauth2_token_uri
                    name: cronjob.extension.liferay.com
              - name: LCP_SERVICE_DOMAIN
                value: localdev.me
              - name: LCP_PROJECT_ID
                value: dxp
              - name: WEBSERVER_SERVICE_HOST
                value: ""