apiVersion: v1
kind: ConfigMap
metadata:
  name: cronjob-dxp-configs
  labels:
    cloud.liferay.com/serviceId: cronjob
    dxp.liferay.com/configs: "true"
    projectCustomer: "yes"
    projectId: lcd13977
    projectSandbox: ""
    projectTrial: "no"
    projectType: ""
  annotations:
    cloud.liferay.com/context-data: '{"domains":["cronjob.localdev.me"]}'
data:
  com.liferay.oauth2.application.factory.headless.server.configuration.v1.Oauth2ApplicationHeadlessServerConfiguration-cronjob.config: |
    name="$[conf:cloud.liferay.com.serviceId]"
    homePageURL="https://$[conf:cloud.liferay.com.domain.0]"
    description="This a custom cronjob DEMO"
    scopes=["Liferay.Headless.Admin.User.everything"]