<?xml version="1.0"?>

<project name="jstl-impl" basedir="." default="compile" xmlns:antelope="antlib:ise.antelope.tasks">
	<property name="project.dir" value="../.." />

	<import file="../../build-common-java.xml" />

	<property name="deploy.dir" value="${module.framework.lib.dir}" />
	<property name="jar.file" value="${ant.project.name}" />

	<path id="module-lib.classpath">
		<fileset dir="${project.dir}/portal-modules/jstl-impl/lib" includes="org.apache.taglibs.standard.glassfish-1.2.0.v201112081803.jar" />
	</path>

	<target name="compile">
		<mkdir dir="${module.src.dir}"/>
		<mkdir dir="tmp"/>

		<unjar
			dest="tmp"
			src="org.apache.taglibs.standard.glassfish-1.2.0.v201112081803-sources.jar"
		/>

		<copy overwrite="true" todir="${module.src.dir}">
			<fileset
				dir="tmp"
				includes="org/apache/taglibs/standard/tlv/JstlBaseTLV.java"
			/>
		</copy>

		<delete dir="tmp" />

		<patch dir="${module.src.dir}" patchfile="patches/patch-1.patch" strip="1" />

		<mkdir dir="${module.classes.dir}" />

		<antcall target="build-common-java.compile" />
	</target>
</project>