apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamicjscss
  labels:
    app: dynamicjscss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamicjscss
  template:
    metadata:
      labels:
        app: dynamicjscss
    spec:
      containers:
      - name: dynamicjscss
        image: dynamicjscss
        imagePullPolicy: Never
        resources:
          limits:
            memory: "50Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/liferay/lxc/dxp-metadata
          name: lxc-dxp-metadata
          readOnly: true
        - mountPath: /etc/liferay/lxc/ext-init-metadata
          name: lxc-ext-init-metadata
          readOnly: true
      volumes:
        - name: lxc-dxp-metadata
          configMap:
            name: lxc-dxp-metadata
        - name: lxc-ext-init-metadata
          configMap:
            name: dynamicjscss-lxc-ext-init-metadata
            optional: true
