<?xml version="1.0"?>

<project name="jasper-initializer" basedir="." default="compile" xmlns:antelope="antlib:ise.antelope.tasks">
	<property name="project.dir" value="../.." />

	<import file="../../build-common-java.xml" />

	<property name="deploy.dir" value="${module.framework.lib.dir}" />
	<property name="jar.file" value="${ant.project.name}" />

	<var name="module.dependencies" value="web-extender" />
</project>