apiVersion: v1
kind: ConfigMap
metadata:
  name: dxp-configmap
  labels:
    app: dxp
data:
  com.liferay.k8s.agent.configuration.v1.K8sAgentConfiguration.config: |
    namespace="$[secret:namespace]"
    labelSelector="dxp=configmap"
  com.liferay.portal.security.sso.openid.connect.internal.configuration.OpenIdConnectProviderConfiguration-googleoidcprovider.config: |
    authorizationEndPoint=""
    companyId=L"20099"
    discoveryEndPoint="https://accounts.google.com/.well-known/openid-configuration"
    discoveryEndPointCacheInMillis=L"360000"
    idTokenSigningAlgValues=[ \
      "RS256", \
      ]
    issuerURL=""
    jwksURI=""
    openIdConnectClientId="$[secret:google.oidc.client.id]"
    openIdConnectClientSecret="$[secret:google.oidc.client.secret]"
    providerName="Google"
    registeredIdTokenSigningAlg=""
    scopes="openid\ email\ profile"
    subjectTypes=[ \
      ]
    tokenConnectionTimeout=I"1000"
    tokenEndPoint=""
    userInfoEndPoint=""
  com.liferay.portal.security.sso.openid.connect.configuration.OpenIdConnectConfiguration.config: |
    enabled=B"true"
  com.liferay.oauth2.provider.rest.internal.spi.bearer.token.provider.configuration.DefaultBearerTokenProviderConfiguration.config: |
    access.token.expires.in=I"60000"
    access.token.key.byte.size=I"32"
    refresh.token.expires.in=I"604800"
    refresh.token.key.byte.size=I"32"
