apiVersion: v1
kind: ConfigMap
metadata:
  name: dxp-configmap
data:
  com.liferay.kubernetes.config.KubernetesConfigurationAgent.config: |
    namespace="$[secret:namespace]"
    labelSelector="dxp=configmap"
    enableHTTP2Logging=B"false"
    enableTaskRunnerLogging=B"true"
  com.liferay.portal.security.sso.openid.connect.internal.configuration.OpenIdConnectProviderConfiguration-googleoidcprovider.config: |
    authorizationEndPoint=""
    companyId=L"20099"
    discoveryEndPoint="https://accounts.google.com/.well-known/openid-configuration"
    discoveryEndPointCacheInMillis=L"360000"
    idTokenSigningAlgValues=[ \
      "RS256", \
      ]
    issuerURL=""
    jwksURI=""
    openIdConnectClientId="$[secret:google.oidc.client.id]"
    openIdConnectClientSecret="$[secret:google.oidc.client.secret]"
    providerName="Google"
    registeredIdTokenSigningAlg=""
    scopes="openid\ email\ profile"
    subjectTypes=[ \
      ]
    tokenConnectionTimeout=I"1000"
    tokenEndPoint=""
    userInfoEndPoint=""
  com.liferay.portal.security.sso.openid.connect.configuration.OpenIdConnectConfiguration.config: |
    enabled=B"true"
  felix.cm.config.plugins: org.apache.felix.configadmin.plugin.interpolation
  foo.config: |
    foo="baz"
  module.framework.system.packages.extra: "com.microsoft.sqlserver.jdbc,com.mysql.cj.jdbc,com.mysql.jdbc,com.p6spy.engine.spy,com.sun.security.auth.module,org.hsqldb.jdbc,org.mariadb.jdbc,sun.misc,sun.net.util,sun.security.provider,javax.websocket,javax.websocket.server,org.apache.tomcat.websocket.server,com.sun.net.httpserver"
  org.apache.felix.configadmin.plugin.interpolation.file.encoding: "UTF-8"
  org.apache.felix.configadmin.plugin.interpolation.secretsdir: "/opt/liferay/osgi/configs,/var/run/secrets/kubernetes.io/serviceaccount"
