apiVersion: v1
kind: ConfigMap
metadata:
  name: dxp-logging-configmap
  labels:
    app: dxp
data:
  # property-like keys; each key maps to a simple value
  com.liferay.k8s.agent-log4j-ext.xml: |
    <?xml version="1.0"?>
    <!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">
    <log4j:configuration xmlns:log4j="http://jakarta.apache.org/log4j/">
        <category name="com.liferay.k8s.agent">
            <priority value="DEBUG" />
        </category>
        <category name="io.kubernetes">
            <priority value="DEBUG" />
        </category>
        <category name="okhttp3">
            <priority value="DEBUG" />
        </category>
    </log4j:configuration>
  com.liferay.oauth2.application.factory-log4j-ext.xml: |
    <?xml version="1.0"?>
    <!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">
    <log4j:configuration xmlns:log4j="http://jakarta.apache.org/log4j/">
        <category name="com.liferay.oauth2.application.factory">
            <priority value="DEBUG" />
        </category>
    </log4j:configuration>
