resources:
- dxp-configmap.yaml
- dxp-deployment.yaml
- dxp-ingress.yaml
- dxp-logging-configmap.yaml
- dxp-role-and-binding.yaml
- dxp-service.yaml
- dxp-volume.yaml
configMapGenerator:
- name: google-oidc-credentials-configmap
  envs:
  - ENV