##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/source-formatter.properties
## for available properties.
##

    line.length.excludes=\
        modules/apps/foundation/messaging/messaging-test/src/main/java/com/liferay/messaging/test/DestinationConfigurationTest.java@64,\
        modules/apps/foundation/messaging/messaging-test/src/main/java/com/liferay/messaging/test/DestinationTest.java@88,\
        modules/apps/foundation/messaging/messaging-test/src/main/java/com/liferay/messaging/test/DestinationTest.java@139
