##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/source-formatter.properties
## for available properties.
##

    source.formatter.excludes=\
        modules/apps/foundation/messaging/messaging-test/src/main/java/com/liferay/messaging/tb10/TBMessageListener.java,\
        modules/apps/foundation/messaging/messaging-test/src/main/java/com/liferay/messaging/tb11/TBMessageListener.java,\
        modules/apps/foundation/messaging/messaging-test/src/main/java/com/liferay/messaging/tb12/TBMessageListener.java,\
        modules/apps/foundation/messaging/messaging-test/src/main/java/com/liferay/messaging/tb1/TBMessageListener.java,\
        modules/apps/foundation/messaging/messaging-test/src/main/java/com/liferay/messaging/tb21/TBMessageListener.java,\
        modules/apps/foundation/messaging/messaging-test/src/main/java/com/liferay/messaging/tb2/TBMessageListener.java,\
        modules/apps/foundation/messaging/messaging-test/src/main/java/com/liferay/messaging/tb3/TBMessageListener.java,\
        modules/apps/foundation/messaging/messaging-test/src/main/java/com/liferay/messaging/tb4/TBMessageListener.java,\
        modules/apps/foundation/messaging/messaging-test/src/main/java/com/liferay/messaging/tb5/TBMessageListener.java,\
        modules/apps/foundation/messaging/messaging-test/src/main/java/com/liferay/messaging/tb6/TBMessageListener.java,\
        modules/apps/foundation/messaging/messaging-test/src/main/java/com/liferay/messaging/tb7/TBMessageListener.java,\
        modules/apps/foundation/messaging/messaging-test/src/main/java/com/liferay/messaging/tb8/TBMessageListener.java,\
        modules/apps/foundation/messaging/messaging-test/src/main/java/com/liferay/messaging/tb9/TBMessageListener.java

    line.length.excludes=\
        modules/apps/foundation/messaging/messaging-test/src/main/java/com/liferay/messaging/test/DestinationConfigurationTest.java@66,\
        modules/apps/foundation/messaging/messaging-test/src/main/java/com/liferay/messaging/test/DestinationTest.java@74,\
        modules/apps/foundation/messaging/messaging-test/src/main/java/com/liferay/messaging/test/DestinationTest.java@125