dependencies {
	compileInclude group: "org.jboss.aerogear.windows", name: "java-mpns", version: "0.1.0"

	compileOnly group: "biz.aQute.bnd", name: "biz.aQute.bndlib", version: "3.1.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "org.apache.httpcomponents", name: "httpclient-osgi", version: "4.5.5"
	compileOnly group: "org.apache.httpcomponents", name: "httpcore-osgi", version: "4.4.9"
	compileOnly project(":apps:push-notifications:push-notifications-api")
	compileOnly project(":core:petra:petra-string")
}