apiVersion: v1
kind: Secret
metadata:
    name: {{ include "liferay.name" . }}
    namespace: {{ include "liferay.namespace" . }}
    labels:
        {{- include "liferay.labels" . | nindent 8 }}
    {{- with .Values.configmap.annotations }}
    annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
type: Opaque
data:
    LIFERAY_DEFAULT_PERIOD_ADMIN_PERIOD_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}