apiVersion: skaffold/v2beta28
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: k8s-native-dxp
    custom:
      buildCommand: ./gradlew resolve buildDockerImage -Pdocker.image.id=$IMAGE
      dependencies:
        paths:
        - modules/**/*
  - image: remote-app-a
    custom:
      buildCommand: lxc-extensions/liferay-hello-world/build.sh
      dependencies:
        paths:
        - lxc-extensions/liferay-hello-world/public
        - lxc-extensions/liferay-hello-world/src
        - lxc-extensions/liferay-hello-world/package.json
        - lxc-extensions/liferay-hello-world/build.sh
  - image: custom-rest-service
    custom:
      buildCommand: lxc-extensions/custom-rest-service/build.sh
      dependencies:
        paths:
        - lxc-extensions/custom-rest-service/src/**/*
        - lxc-extensions/custom-rest-service/pom.xml
  - image: cronjob
    custom:
      buildCommand: lxc-extensions/cronjob/build.sh
      dependencies:
        paths:
        - lxc-extensions/cronjob/curl.sh
deploy:
  kustomize:
    paths:
    - k8s/dxp/
    - k8s/remoteappa/
    - k8s/custom-rest-service/
    - k8s/cronjob/
    - k8s/common/
    hooks:
      after:
      - host:
          command: ["./darwin_patch.sh"]
          os:
          - darwin