checkstyle.chaining.check.allowedMethodNames=\
	configMaps

source.formatter.excludes=\
	**/com/liferay/oauth2/application/factory/dynamicinclude/OAuth2ApplicationsDynamicInclude.java,\
	**/com/liferay/oauth2/application/factory/servlet/OAuth2RedirectServlet.java