v1alpha1.extension_repo(name='default', url='https://github.com/gamerson/tilt-extensions')

custom_build(
  'k8s-native-dxp',
  command='./gradlew clean buildDockerImage -Pdocker.image.id=$EXPECTED_REF',
  deps=['./modules'],
  ignore=['**/build']
)

k8s_yaml(kustomize('k8s/dxp'))
k8s_yaml(kustomize('k8s/common'))

k8s_resource(
  workload='dxp-deployment',
  links=[
    link('dxp.localdev.me', 'DXP')
  ],
  port_forwards=[
    port_forward(8000, name='Debug DXP @ 8000'),
    port_forward(11311, name='Telnet DXP @ 11311')
  ]
)

for extensionDir in str(local("find ./*/ -type f -name Tiltfile -not -path '*/bin/*' | sed -E 's|/[^/]+$||' |sort -u")).splitlines():
  include('%s/Tiltfile' % extensionDir)
  print(os.path.basename(extensionDir))