v1alpha1.extension_repo(name='default', url='https://github.com/gamerson/tilt-extensions')

custom_build(
  'k8s-native-dxp',
  command='./gradlew resolve buildDockerImage -Pdocker.image.id=$EXPECTED_REF',
  deps=['./modules'],
  ignore=['**/build']
)

k8s_yaml(kustomize('k8s/dxp'))
k8s_yaml(kustomize('k8s/common'))

for tiltfile in str(local("find ./*/ -name Tiltfile")).splitlines():
  include(tiltfile)