apiVersion: apps/v1
kind: Deployment
metadata:
  name: liferayhelloworld
  labels:
    app: liferayhelloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liferayhelloworld
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: liferayhelloworld
    spec:
      containers:
      - name: liferayhelloworld
        image: liferayhelloworld
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "200m"
            memory: "50Mi"
        volumeMounts:
        - mountPath: /etc/liferay/lxc/dxp-metadata
          name: lxc-dxp-metadata
          readOnly: true
        - mountPath: /etc/liferay/lxc/ext-init-metadata
          name: lxc-ext-init-metadata
          readOnly: true
      volumes:
        - name: lxc-dxp-metadata
          configMap:
            name: lxc-dxp-metadata
        - name: lxc-ext-init-metadata
          configMap:
            name: liferayhelloworld-lxc-ext-init-metadata
            optional: true

